-- Your SQL goes here

-- ALTER TABLE users ADD COLUMN permission SMALLINT NOT NULL DEFAULT 3;

ALTER TABLE tagruts ADD COLUMN tag_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tagitems ADD COLUMN tag_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tagetcs ADD COLUMN tag_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
